### ISSUE TITLE
Site name change

### ISSUE THREAD

**Issue by whitep4nth3r** [brittneypostma/abcs-of-netlify#1]
Hello!

How about changing the site name live URL to abcs-of.netlify.app — so `netlify` isn't repeated in the URL?

**Comment by brittneypostma** [comment]
nice one, will do!

**Comment by brittneypostma** [comment]
https://abcs-of.netlify.app/ Done. Something that was brought up is forwarding to [abcs-of.netlify.com](http://abcs-of.netlify.com/) after it is done.

**Comment by whitep4nth3r** [comment]
Nah, too much overhead! And plus, keeping Netlify sites on the netlify app domain is... you know, meta!
